### ISSUE TITLE
[Redacted]

### ISSUE THREAD

**Issue by HeyItsMicro** [magnetardev/Start#1]
[Redacted]

**Comment by HeyItsMicro** [comment]
Can you please reopen this issue as it has not even been discussed, thanks.

**Comment by magnetardev** [comment]
Too vulgar to be worked on. We need to consider the byte size of this site and minimize JavaScript usage to speed up page load. Excess features or information will only serve as bloat. Will not fix!

**Comment by HeyItsMicro** [comment]
My name is Mike Penis. I’m named after my dad’s penis.
